AWSTemplateformateVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Deploying Resources for AWS

Parameters:
  awssecuritygroupid:
    Type: String
    Description: Required for AWS functions creation
  awssubnetid1:
    Type: String
    Description: Required for AWS functions creation
  awssubnetid2:
    Type: String
    Description: Required for AWS functions creation
  lambdaRole:
    Type: String
    Description: Required for Lambda functions creation
  awsRegion:
    Type: String
    Description: Required for Lambda functions creation
     
Resources:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: aws_lambda.py
      CodeUri: app/aws_lambda.py
      Description: "Lambda example"
      Environment:
        Variables:
          awsRegion: !Ref awsRegion
      Role: !Ref lambdaRole
      Handler: index.lambda_handler
      Runtime: python3.9
      Timeout: 900
      VpcConfig:
        SecurityGroupIds:
          - !Ref awssecuritygroupid
        SubnetIds:
          - !Ref awssubnetid1
          - !Ref awssubnetid2